# Generated by Django 2.2.4 on 2019-11-26 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('baiviet_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tieude', models.CharField(max_length=300)),
                ('noidung', models.TextField()),
                ('ngay_dang', models.DateTimeField(default=django.utils.timezone.now)),
                ('anhbia', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=3000)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('accept', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('custom', models.CharField(max_length=200)),
                ('address', models.TextField(default='', max_length=1000)),
                ('phone', models.CharField(default='', max_length=15)),
                ('total', models.FloatField()),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('payment_status', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('accept', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('product_img', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('investory', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(default='', max_length=255)),
                ('pro_price', models.IntegerField()),
                ('pro_image', models.CharField(default='', max_length=255)),
                ('quantity', models.IntegerField()),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Order')),
            ],
        ),
    ]
